# Generated by Django 4.2.5 on 2023-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderData', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('producy', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
