# Generated by Django 4.2.5 on 2023-11-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='records',
            name='producy',
        ),
        migrations.RemoveField(
            model_name='records',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='records',
            name='unit',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.records')),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='products',
            field=models.ManyToManyField(through='website.OrderProduct', to='website.product'),
        ),
    ]
