# Generated by Django 4.2.5 on 2023-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_quantity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='OrderData',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='OrderData',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
